# Phase 2: Data Cleaning

## Objective

The goal of this notebook is to prepare a clean, consistent dataset for exploratory data analysis (EDA) and feature engineering.

In this phase, we will:

- Merge the sales and store datasets.
- Validate the merge operation.
- Convert the `Date` column to the appropriate datetime format.
- Audit missing values and classify their causes.
- Create a dataset containing only open stores for model training.
- Save the cleaned datasets for use in later phases.

### Important Principles

- Raw datasets remain unchanged.
- Every preprocessing decision must be justified.
- Missing values will be understood before being treated.
- Cleaning is separated from feature engineering.

In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df=pd.read_csv("../data/raw/train.csv")
store_df=pd.read_csv("../data/raw/store.csv")

C:\Users\ragha\AppData\Local\Temp\ipykernel_24720\3568736666.py:1: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df=pd.read_csv("../data/raw/train.csv")

In [5]:
print(f"Train shape : {train_df.shape}")
print(f"Store shape : {store_df.shape}")

Train shape : (1017209, 9)
Store shape : (1115, 10)

In [9]:
merged_df=train_df.merge(store_df,on="Store",how="left")

In [10]:
print("Merged Shape:", merged_df.shape)

Merged Shape: (1017209, 18)

In [11]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  str
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  str
 10  Assortment                 1017209 non-null  str
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   str
dtypes: float64(5), int64(8), object(1), str(4)
memory usage: 139.7+ MB

In [12]:
merged_df.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.014567e+06,693861.000000,693861.000000,1.017209e+06,509178.000000,509178.000000
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01,5.430086e+03,7.222866,2008.690228,5.005638e-01,23.269093,2011.752774
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01,7.715324e+03,3.211832,5.992644,4.999999e-01,14.095973,1.662870
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,1.000000,1900.000000,0.000000e+00,1.000000,2009.000000
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00,7.100000e+02,4.000000,2006.000000,0.000000e+00,13.000000,2011.000000
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00,2.330000e+03,8.000000,2010.000000,1.000000e+00,22.000000,2012.000000
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00,6.890000e+03,10.000000,2013.000000,1.000000e+00,37.000000,2013.000000
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00,7.586000e+04,12.000000,2015.000000,1.000000e+00,50.000000,2015.000000

In [13]:
merged_df.describe(include=object)

C:\Users\ragha\AppData\Local\Temp\ipykernel_24720\3395907174.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  merged_df.describe(include=object)

              Date StateHoliday StoreType Assortment    PromoInterval
count      1017209      1017209   1017209    1017209           509178
unique         942            5         4          3                3
top     2015-07-31            0         a          a  Jan,Apr,Jul,Oct
freq          1115       855087    551627     537445           293122

In [14]:
merged_df["Date"]=pd.to_datetime(merged_df["Date"])

In [15]:
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[us]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  str
 10  Assortment                 1017209 non-null  str
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   str
dtypes: datetime64[us](1), float64(5), int64(8), object(1), str(3)
memory usage: 139.7+ MB

In [ ]:
missing_values = merged_df.isnull().sum()
missing_values = missing_values[missing_values > 0]
missing_values.sort_values(ascending=False)

Promo2SinceYear              508031
Promo2SinceWeek              508031
PromoInterval                508031
CompetitionOpenSinceMonth    323348
CompetitionOpenSinceYear     323348
CompetitionDistance            2642
dtype: int64

## Merge Validation

The sales dataset was merged with the store metadata using a left join on the `Store` column.

Validation checks confirmed that:

- The number of rows remained unchanged.
- No duplicate records were introduced.
- Every sales record successfully matched with store metadata.
- The merged dataset contains 18 columns.

These checks confirm that the merge was successful and no information was lost.

## Date Conversion

The `Date` column was converted from the `object` data type to `datetime64[ns]`.

This enables efficient chronological operations and prepares the dataset for future temporal feature engineering (e.g., extracting year, month, or weekday).

In [20]:
merged_df.groupby("Promo2")[[
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "PromoInterval"
]].apply(lambda x: x.isnull().sum())

        Promo2SinceWeek  Promo2SinceYear  PromoInterval
Promo2
0                508031           508031         508031
1                     0                0              0

In [19]:
missing_percentage = (missing_values / len(merged_df) * 100).round(2)
missing_summary = pd.DataFrame({
    "Missing Count": missing_values,
    "Missing Percentage": missing_percentage
})
missing_summary

                           Missing Count  Missing Percentage
CompetitionDistance                 2642                0.26
CompetitionOpenSinceMonth         323348               31.79
CompetitionOpenSinceYear          323348               31.79
Promo2SinceWeek                   508031               49.94
Promo2SinceYear                   508031               49.94
PromoInterval                     508031               49.94

In [21]:
merged_df[[
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear"
]].isnull().sum()

CompetitionDistance            2642
CompetitionOpenSinceMonth    323348
CompetitionOpenSinceYear     323348
dtype: int64

In [25]:
merged_df[merged_df["CompetitionDistance"].isnull()][
    ["CompetitionDistance", "CompetitionOpenSinceMonth", "CompetitionOpenSinceYear"]
].head(10)

      CompetitionDistance  CompetitionOpenSinceMonth  CompetitionOpenSinceYear
290                   NaN                        NaN                       NaN
621                   NaN                        NaN                       NaN
878                   NaN                        NaN                       NaN
1405                  NaN                        NaN                       NaN
1736                  NaN                        NaN                       NaN
1993                  NaN                        NaN                       NaN
2520                  NaN                        NaN                       NaN
2851                  NaN                        NaN                       NaN
3108                  NaN                        NaN                       NaN
3635                  NaN                        NaN                       NaN

In [26]:
merged_df["Open"].value_counts()

Open
1    844392
0    172817
Name: count, dtype: int64

In [27]:
merged_df.groupby("Open")["Sales"].describe()

         count         mean         std  min     25%     50%     75%      max
Open
0     172817.0     0.000000     0.00000  0.0     0.0     0.0     0.0      0.0
1     844392.0  6955.514291  3104.21468  0.0  4859.0  6369.0  8360.0  41551.0

## Creating the Open Store Dataset

The project aims to forecast sales for stores that are operating.

Closed stores always record zero sales because no transactions can occur. Including these observations in the training dataset would encourage the model to learn the trivial relationship between the `Open` indicator and sales, rather than learning the effects of promotions, seasonality, holidays, and competition.

To focus the model on demand forecasting, a separate dataset containing only open-store observations is created.

In [29]:
train_open_df = merged_df[merged_df["Open"]==1].copy()

In [30]:
train_open_df.info()

<class 'pandas.DataFrame'>
Index: 844392 entries, 0 to 1017190
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Store                      844392 non-null  int64
 1   DayOfWeek                  844392 non-null  int64
 2   Date                       844392 non-null  datetime64[us]
 3   Sales                      844392 non-null  int64
 4   Customers                  844392 non-null  int64
 5   Open                       844392 non-null  int64
 6   Promo                      844392 non-null  int64
 7   StateHoliday               844392 non-null  object
 8   SchoolHoliday              844392 non-null  int64
 9   StoreType                  844392 non-null  str
 10  Assortment                 844392 non-null  str
 11  CompetitionDistance        842206 non-null  float64
 12  CompetitionOpenSinceMonth  575773 non-null  float64
 13  CompetitionOpenSinceYear   575773 non-null  float64
 14  Promo2                     844392 non-null  int64
 15  Promo2SinceWeek            421085 non-null  float64
 16  Promo2SinceYear            421085 non-null  float64
 17  PromoInterval              421085 non-null  str
dtypes: datetime64[us](1), float64(5), int64(8), object(1), str(3)
memory usage: 122.4+ MB

In [31]:
train_open_df.describe()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,844392.000000,844392.000000,844392,844392.000000,844392.000000,844392.0,844392.000000,844392.000000,842206.000000,575773.000000,575773.000000,844392.000000,421085.000000,421085.000000
mean,558.422920,3.520361,2014-04-11 01:02:42.487564,6955.514291,762.728395,1.0,0.446352,0.193580,5457.979627,7.224879,2008.697747,0.498684,23.253426,2011.754019
min,1.000000,1.000000,2013-01-01 00:00:00,0.000000,0.000000,1.0,0.000000,0.000000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,280.000000,2.000000,2013-08-16 00:00:00,4859.000000,519.000000,1.0,0.000000,0.000000,710.000000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,558.000000,3.000000,2014-03-31 00:00:00,6369.000000,676.000000,1.0,0.000000,0.000000,2320.000000,8.000000,2010.000000,0.000000,22.000000,2012.000000
75%,837.000000,5.000000,2014-12-10 00:00:00,8360.000000,893.000000,1.0,1.000000,0.000000,6890.000000,10.000000,2013.000000,1.000000,37.000000,2013.000000
max,1115.000000,7.000000,2015-07-31 00:00:00,41551.000000,7388.000000,1.0,1.000000,1.000000,75860.000000,12.000000,2015.000000,1.000000,50.000000,2015.000000
std,321.731914,1.723689,NaN,3104.214680,401.227674,0.0,0.497114,0.395103,7809.437311,3.210144,5.978048,0.499999,14.100569,1.660962

In [32]:
train_open_df.duplicated().sum()

np.int64(0)

In [33]:
merged_df.to_csv("../data/processed/merged_data.csv", index=False)
train_open_df.to_csv("../data/processed/train_open.csv", index=False)

## Saving Processed Datasets

Two processed datasets were saved:

- `merged_data.csv` — complete cleaned dataset for exploratory analysis and reporting.
- `train_open.csv` — dataset containing only open-store observations for feature engineering and model development.

Saving processed data avoids repeating preprocessing in future notebooks and improves the reproducibility of the workflow.